/*
 * ePDF Engine (epdf-org) — an open-source PDF engine and toolkit.
 * Part of the ePDF Engine project.  Copyright (c) 2026 Rupesh Borse.
 *
 * Licensed under the ePDF Engine License, a permissive open-source license:
 * you may freely use, copy, modify, and distribute this software (including in
 * commercial or closed-source products) provided this notice and the LICENSE
 * file are retained. See LICENSE at the repository root for the full terms.
 *
 * Original clean-room work: no third-party or copyleft (AGPL/GPL) code.
 * Cryptography is intentionally out of scope for epdf-org.
 *
 * Author: Rupesh Borse
 */
package com.epdfengine.rb.org.core;

import com.epdfengine.rb.org.css.CssParser;
import com.epdfengine.rb.org.css.ComputedStyle;
import com.epdfengine.rb.org.css.FitMode;
import com.epdfengine.rb.org.css.PageRule;
import com.epdfengine.rb.org.css.StyleResolver;
import com.epdfengine.rb.org.common.Length;
import com.epdfengine.rb.org.html.HtmlNode;
import com.epdfengine.rb.org.html.HtmlParser;
import com.epdfengine.rb.org.io.font.FontRegistry;
import com.epdfengine.rb.org.layout.ApproxTextMeasurer;
import com.epdfengine.rb.org.layout.LaidOutDocument;
import com.epdfengine.rb.org.layout.LayoutEngine;
import com.epdfengine.rb.org.layout.LayoutParams;
import com.epdfengine.rb.org.layout.TextMeasurer;
import com.epdfengine.rb.org.layout.box.BlockBox;
import com.epdfengine.rb.org.pdfa.Conformance;
import com.epdfengine.rb.org.pdfa.ConformanceValidator;
import com.epdfengine.rb.org.pdfa.DocumentMetadata;
import com.epdfengine.rb.org.render.Renderer;

import java.io.IOException;
import java.io.OutputStream;

/**
 * Mode A entry point: HTML + CSS → PDF. Parses the HTML, collects {@code <style>}
 * stylesheets, cascades styles, builds the box tree, lays it out, and renders —
 * reusing the same layout/render/font/SVG pipeline as the programmatic API.
 */
public final class HtmlRenderer {

    /** Default design width (768pt ≈ 1024px) when a fit mode is requested without one. */
    private static final double DEFAULT_DESIGN_WIDTH_PT = 768.0;

    /**
     * Renders an HTML document to PDF bytes.
     *
     * @param html   the HTML source (may include {@code <style>} blocks and inline styles)
     * @param params page geometry (size + margins)
     * @param fonts  optional font registry; when non-null its fonts are embedded,
     *               otherwise the base-14 fonts are used with approximate metrics
     */
    public byte[] render(String html, LayoutParams params, FontRegistry fonts) throws IOException {
        return render(html, params, fonts, null);
    }

    /**
     * Renders an HTML document to PDF bytes, resolving {@code <img src>} references
     * through the supplied {@link ResourceLoader} (raster images and external SVG).
     */
    public byte[] render(String html, LayoutParams params, FontRegistry fonts, ResourceLoader resources)
            throws IOException {
        LaidOutDocument laid = layoutHtml(html, params, fonts, resources);
        return new Renderer().renderToPdf(laid, fonts);
    }

    /**
     * Renders an HTML document to a PDF that targets a {@link Conformance} level
     * (PDF/A-2b, PDF/UA-1, or both). The {@link DocumentMetadata} fills the Info
     * dictionary and XMP packet. For PDF/A all fonts must be embedded — pass a
     * {@link FontRegistry} loaded with embeddable TrueType fonts.
     */
    public byte[] render(String html, LayoutParams params, FontRegistry fonts, ResourceLoader resources,
                         Conformance conformance, DocumentMetadata meta) throws IOException {
        LaidOutDocument laid = layoutHtml(html, params, fonts, resources);
        return new Renderer().renderToPdf(laid, fonts, conformance, meta);
    }

    /**
     * Streams an HTML render straight to {@code out} (no {@code byte[]} held in memory),
     * resolving {@code <img src>} through {@code resources}. The caller owns {@code out}.
     */
    public void renderTo(String html, LayoutParams params, FontRegistry fonts, ResourceLoader resources,
                         OutputStream out) throws IOException {
        LaidOutDocument laid = layoutHtml(html, params, fonts, resources);
        new Renderer().renderTo(laid, fonts, out);
    }

    /** Streams a conformance-targeted HTML render (PDF/A-2b / PDF/UA-1) straight to {@code out}. */
    public void renderTo(String html, LayoutParams params, FontRegistry fonts, ResourceLoader resources,
                         Conformance conformance, DocumentMetadata meta, OutputStream out) throws IOException {
        LaidOutDocument laid = layoutHtml(html, params, fonts, resources);
        new Renderer().renderTo(laid, fonts, conformance, meta, out);
    }

    /**
     * Lays out an HTML document and applies a conformance target, returning the
     * generated bytes together with any conformance issues the generation-side
     * validator detected (empty list = the checked invariants hold).
     */
    public ConformantResult renderConformant(String html, LayoutParams params, FontRegistry fonts,
                                             ResourceLoader resources, Conformance conformance,
                                             DocumentMetadata meta) throws IOException {
        LaidOutDocument laid = layoutHtml(html, params, fonts, resources);
        com.epdfengine.rb.org.kernel.PdfDocument pdf =
                new Renderer().buildPdf(laid, fonts, conformance, meta);
        java.util.List<String> issues = ConformanceValidator.validate(pdf, conformance);
        if (conformance != null && conformance.isPdfUa()) {
            issues = new java.util.ArrayList<>(issues);
            issues.addAll(com.epdfengine.rb.org.pdfua.PdfUaValidator.validateHeadings(laid.structTree()));
        }
        java.io.ByteArrayOutputStream out = new java.io.ByteArrayOutputStream(16 * 1024);
        pdf.writeTo(out);
        return new ConformantResult(out.toByteArray(), issues);
    }

    /** Bytes of a conformance-targeted PDF plus the generation-side validation issues. */
    public record ConformantResult(byte[] bytes, java.util.List<String> issues) {
        public boolean isConformant() { return issues.isEmpty(); }
    }

    /** Lays out an HTML document to a {@link LaidOutDocument} (the CPU-heavy stage), without writing PDF. */
    public LaidOutDocument layout(String html, LayoutParams params, FontRegistry fonts, ResourceLoader resources) {
        return layoutHtml(html, params, fonts, resources);
    }

    /** Shared layout pipeline used by every {@code render}/{@code renderConformant} overload. */
    private LaidOutDocument layoutHtml(String html, LayoutParams params, FontRegistry fonts,
                                       ResourceLoader resources) {
        HtmlNode document = new HtmlParser().parse(html);
        String css = extractStyles(document);
        StyleResolver resolver = new StyleResolver(CssParser.parseStylesheet(css));
        DomToBoxes domToBoxes = new DomToBoxes(resolver, resources);
        domToBoxes.setKeyframes(CssParser.parseKeyframes(css));
        BlockBox root = domToBoxes.build(document);

        // @page: override page size/margins and pick a fit mode (auto-fit extensions).
        LayoutParams eff = params;
        FitMode fit = FitMode.REFLOW;
        boolean autoHeight = false;
        double designWidthPt = DEFAULT_DESIGN_WIDTH_PT;
        PageRule pr = CssParser.parseAtPage(css);
        if (pr != null) {
            if (pr.widthPt() != null && pr.heightPt() != null) {
                eff = eff.withPageSize(pr.widthPt(), pr.heightPt());
            } else if (pr.widthPt() != null) {
                eff = eff.withPageSize(pr.widthPt(), eff.pageHeightPt());
            }
            if (pr.margins() != null) eff = eff.withMargins(pr.margins());
            fit = pr.fit();
            autoHeight = pr.autoHeight();
            if (pr.designWidthPt() != null) {
                designWidthPt = pr.designWidthPt();
            } else if (fit != FitMode.REFLOW) {
                double detected = detectDesignWidthPt(document, resolver);
                if (detected > 0) designWidthPt = detected;
            }
        }

        TextMeasurer measurer = (fonts != null) ? new FontMetricsMeasurer(fonts) : new ApproxTextMeasurer();
        if (autoHeight) {
            // "Long page": lay out on a single max-height page, then trim to content.
            LayoutParams tall = eff.withPageSize(eff.pageWidthPt(), LayoutParams.MAX_PAGE_DIMENSION_PT);
            LaidOutDocument full = new LayoutEngine().layout(root, tall, measurer);
            LaidOutDocument shrunk = full.shrinkToContent(eff.margins().bottom());
            shrunk.setStructTree(domToBoxes.structTree());
            return shrunk;
        } else if (fit == FitMode.REFLOW) {
            LaidOutDocument laid = new LayoutEngine().layout(root, eff, measurer);
            laid.setStructTree(domToBoxes.structTree());
            return laid;
        } else {
            // Lay the design out at its natural width, then uniformly scale it to the
            // target page ("render like an image"); AutoFitter owns the design layout.
            LaidOutDocument laid = AutoFitter.fit(root, eff, fit, designWidthPt, measurer);
            laid.setStructTree(domToBoxes.structTree());
            return laid;
        }
    }

    public byte[] render(String html, LayoutParams params) throws IOException {
        return render(html, params, null);
    }

    /**
     * Detects a natural design width (points) from the {@code <body>} or its top
     * wrapper's fixed {@code max-width}/{@code width}, so auto-fit scales from the
     * author's intended canvas rather than a fixed default. Returns -1 if none.
     */
    private static double detectDesignWidthPt(HtmlNode document, StyleResolver resolver) {
        HtmlNode body = findTag(document, "body");
        HtmlNode base = (body != null) ? body : document;
        double best = fixedWidthPt(base, resolver);
        if (best > 0) return best;
        for (HtmlNode c : base.children()) {           // e.g. a `.container` / `.page` wrapper
            if (!c.isElement()) continue;
            double w = fixedWidthPt(c, resolver);
            if (w > best) best = w;
        }
        return best;
    }

    private static double fixedWidthPt(HtmlNode element, StyleResolver resolver) {
        ComputedStyle cs = resolver.resolve(element, null);
        double em = cs.fontSizePt();
        Length mw = cs.maxWidth();
        if (mw != null && !mw.isAuto() && !mw.isPercent()) {
            double v = mw.resolve(em, em, 0);
            if (v > 1) return v;
        }
        Length w = cs.width();
        if (w != null && !w.isAuto() && !w.isPercent()) {
            double v = w.resolve(em, em, 0);
            if (v > 1) return v;
        }
        return -1;
    }

    private static HtmlNode findTag(HtmlNode node, String tag) {
        if (node.isElement() && tag.equals(node.tagName())) return node;
        for (HtmlNode c : node.children()) {
            HtmlNode found = findTag(c, tag);
            if (found != null) return found;
        }
        return null;
    }

    private static String extractStyles(HtmlNode node) {
        StringBuilder sb = new StringBuilder();
        collectStyles(node, sb);
        return sb.toString();
    }

    private static void collectStyles(HtmlNode node, StringBuilder sb) {
        if (node.isElement() && "style".equals(node.tagName())) {
            sb.append(node.textContent()).append('\n');
        }
        for (HtmlNode c : node.children()) collectStyles(c, sb);
    }
}
